### ISSUE TITLE
Conflict with company-quickhelp-mode

### ISSUE THREAD

**Issue by seagle0128** [tumashu/company-posframe#1]
`company-quickhelp-mode` will make posframe close automatically. Any alternative for it? or any plan to port `company-quickhelp` to posframe? Thanks!

**Comment by tumashu** [comment]
At the moment, no plan, but, PR is welcome :-)

**Comment by c0001** [comment]
The same  conflicted question for me and with none ability for fixing or PR it 😺 .

Sitting for waiting for the feature adding by @tumashu '大佬' .

**Comment by ermingol23** [comment]
I have found the reason for why company-quickhelp tooltip hides company-posframe; the hook window-configuration-change-hook gets called when a tooltip is shown and that in turn triggers company-posframe to hide its posframe...

Thus the solution to the problem is to add a guard (e.g. if-statement) to company-posframe-hide that ensures that the posframe is not hidden when a popup is shown but hides it when window is switched. :-)

**Comment by ermingol23** [comment]
I have verified that modifying company-posframe.el like this solves this issue (I am not able to send you a PR, but this change is trivial anyway). The idea is to add a new function that gets called from the `window-configuration-change-hook` instead of `company-posframe-hide`. This new function depends on a global variable that stores the selected window when the company-posframe was shown. The heuristics used is that if window-configuration-change-hook gets called and (selected-window) differs from the cached value then the user switched windows. Otherwise, it is assumed that a tooltip or posframe etc. was shown. In the former case company-posframe is hidden and in the latter case nothing happens.

> (defvar company-posframe-window nil
>   "Window containing company-posframe if it is showing.")
> 
> (defun company-posframe-show ()
>   "Show company-posframe candidate menu."
>   (let* (...)
>     ...
>     (setq company-posframe-window (selected-window))
>     ...))
> 
> (defun company-posframe-window-configuration-changed ()
>   "Function called from `window-configuration-change-hook`."
>   (if (not (eq company-posframe-window (selected-window)))
>     (company-posframe-hide)))
> 
> (defun company-posframe-hide ()
>   "Hide company-posframe candidate menu."
>   (posframe-hide company-posframe-buffer)
>   (setq company-posframe-window nil))

and in "define-minor-mode" replace
`(add-hook 'window-configuration-change-hook #'company-posframe-hide)`
with
`(add-hook 'window-configuration-change-hook #'company-posframe-window-configuration-changed-hook)`

and conversely
`(remove-hook 'window-configuration-change-hook #'company-posframe-hide)`
with
`(remove-hook 'window-configuration-change-hook #'company-posframe-window-configuration-changed-hook)`

**Comment by seagle0128** [comment]
@tumashu Would you please consider merging @ermingol23 's solution? Which looks good.

**Comment by ylluminarious** [comment]
@tumashu I would also appreciate it if you would merge @ermingol23's solution above. Auto-complete recently died (the maintainers archived the project) so `company-mode` is the only solution for auto-completion in Emacs now. This package helps solve [issues with zooming in,](https://github.com/company-mode/company-mode/issues/299) so it would be nice if it was able to work with `company-quickhelp`.

**Comment by tumashu** [comment]
auto-complete died?

**Comment by seagle0128** [comment]
Now I have to switch to [company-box](https://github.com/sebastiencs/company-box) although it's not perfect.

**Comment by ylluminarious** [comment]
@tumashu Well, if you look at [their organization page](https://github.com/auto-complete) you can see that three of their main projects are archived. Namely, `auto-complete`, `popup.el` and `fuzzy.el`. This means no one can make new pull requests or comment on issues. This effectively means no more new development can occur without forking the projects and it puts the code in a read-only state. Since `company-mode` exists, I doubt anyone will fork it. [We actually discussed this problem here,](https://github.com/auto-complete/auto-complete/issues/503) but no one was able to take up the torch (including myself).

**Comment by ylluminarious** [comment]
@seagle0128 Does `company-box` work with `company-posframe`? Does it also provide the same functionality as `company-quickhelp`?

**Comment by seagle0128** [comment]
@tumashu `auto-compelete` are archived and died...

@ylluminarious `company-box` provides same functionalities of `company-posframe`, plus `quck help` and `icon`, like this:

![image](https://user-images.githubusercontent.com/140797/59013075-b28d6580-886b-11e9-9a0c-be9dccb1a21b.png)

**Comment by tumashu** [comment]
company-box 看起来也很赞

**Comment by seagle0128** [comment]
@tumashu 是不错，可惜有些bug，性能也有点问题，作者似乎不积极更新，提交了issue和PR都不怎么理，不如大佬勤快啊 ~~~

**Comment by tumashu** [comment]
Please test: https://github.com/tumashu/company-posframe/tree/quickhelp

**Comment by seagle0128** [comment]
@tumashu 我简单测试了下，在27上一闪窗口就没了。

**Comment by tumashu** [comment]
![1](https://user-images.githubusercontent.com/67725/59072013-861d2c00-88f3-11e9-9d97-750bdd2a41a7.gif)

**Comment by tumashu** [comment]
我这边效果是这样子的

**Comment by tumashu** [comment]
![图片](https://user-images.githubusercontent.com/67725/59141749-3fa7fa00-89e5-11e9-8d03-f2f0b533988e.png)

**Comment by tumashu** [comment]
@seagle0128 I have add a PR to company-quickhelp,  you can try:
```
(setq company-quickhelp-tooltip 'posframe)
```

**Comment by seagle0128** [comment]
@tumashu I tried d7e0bd9e063c7e52a0dbcde79df0e4b2e7a4f3e7, and it works well, except one minor issue: `C-g` is unable hide the doc window.

Will this be merged into the upstream?

**Comment by ylluminarious** [comment]
@tumashu It looks like your PR was rejected by the upstream developer of `company-quickhelp`. What should we do now in order to resolve this issue? Also, do you know what's causing the problem reported by @seagle0128? Thanks for your work on this issue so far.

**Comment by tumashu** [comment]
I do not know, the best way is merging to company-quickhelp,  for I do not want to maintain many advice in company-posframe, may be we have other way ...

**Comment by ylluminarious** [comment]
@tumashu Yes, it's really too bad the developer turned you down. What is the other way you have in mind?

**Comment by ema2159** [comment]
> @tumashu Yes, it's really too bad the developer turned you down. What is the other way you have in mind?

That's just wrong. If he claims he doesn't have much time to maintain his package `(company-quickhelp` author) he should seek for a new maintainer or at least get help for maintaining the package.

**Comment by tumashu** [comment]
https://github.com/tumashu/company-posframe/blob/master/company-posframe-quickhelp.el
